// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbR7M7EPU1RgEel-kpy4FEswZWjtWGREI',
    appId: '1:1098041927641:web:ec26c7723721ffd7641bc8',
    messagingSenderId: '1098041927641',
    projectId: 'final-project-19699',
    authDomain: 'final-project-19699.firebaseapp.com',
    storageBucket: 'final-project-19699.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_nSPvo1ruAht6OsokjoeuSO4UKMMU8sc',
    appId: '1:1098041927641:android:f631cec905f96f7f641bc8',
    messagingSenderId: '1098041927641',
    projectId: 'final-project-19699',
    storageBucket: 'final-project-19699.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBovzbZkh586DAb3red-MfKEGVUeEMcDaw',
    appId: '1:1098041927641:ios:afc20faacdce93d2641bc8',
    messagingSenderId: '1098041927641',
    projectId: 'final-project-19699',
    storageBucket: 'final-project-19699.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBovzbZkh586DAb3red-MfKEGVUeEMcDaw',
    appId: '1:1098041927641:ios:afc20faacdce93d2641bc8',
    messagingSenderId: '1098041927641',
    projectId: 'final-project-19699',
    storageBucket: 'final-project-19699.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbR7M7EPU1RgEel-kpy4FEswZWjtWGREI',
    appId: '1:1098041927641:web:f90fe187d1b4bf05641bc8',
    messagingSenderId: '1098041927641',
    projectId: 'final-project-19699',
    authDomain: 'final-project-19699.firebaseapp.com',
    storageBucket: 'final-project-19699.appspot.com',
  );

}